/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

/**
 *
 * @author layon
 */
public class ProjetoEstimativaView extends javax.swing.JFrame {

    /**
     * Creates new form TelaEstimativa
     */
    public ProjetoEstimativaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbGrande = new javax.swing.JCheckBox();
        cbPequeno = new javax.swing.JCheckBox();
        cbMedio = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        cbBasico = new javax.swing.JCheckBox();
        cbProfissional = new javax.swing.JCheckBox();
        cbMVP = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        cbCadastroEmailSenha = new javax.swing.JCheckBox();
        cbCadastroFacebook = new javax.swing.JCheckBox();
        cbEmailConviteUsuario = new javax.swing.JCheckBox();
        cbCadastroTwitter = new javax.swing.JCheckBox();
        cbCadastroGithub = new javax.swing.JCheckBox();
        cbCadastroLinkedin = new javax.swing.JCheckBox();
        cbCadastroGoogle = new javax.swing.JCheckBox();
        cbSubdominios = new javax.swing.JCheckBox();
        cbContasMultiTenant = new javax.swing.JCheckBox();
        cbDominiosPesonalizados = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        cbPainel = new javax.swing.JCheckBox();
        cbFeedAtividade = new javax.swing.JCheckBox();
        cbTags = new javax.swing.JCheckBox();
        cbUploadArquivos = new javax.swing.JCheckBox();
        cbEmailTransacionais = new javax.swing.JCheckBox();
        cbPerfisUsuario = new javax.swing.JCheckBox();
        cbUploadMidia = new javax.swing.JCheckBox();
        cbProcessamentoAudioVideo = new javax.swing.JCheckBox();
        cbAvaliacoesComentarios = new javax.swing.JCheckBox();
        cbPesquisa = new javax.swing.JCheckBox();
        cbPesquisaTextoLivre = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        cbMensagens = new javax.swing.JCheckBox();
        cbForunsComentarios = new javax.swing.JCheckBox();
        cbIntegracaoFacebookOpenGraph = new javax.swing.JCheckBox();
        cbCompartilhamentoSocial = new javax.swing.JCheckBox();
        cbNotificacoesPush = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        cbCalendario = new javax.swing.JCheckBox();
        cbExibicaoDadosMapaGeolocalizacoes = new javax.swing.JCheckBox();
        cbExibicaoMercadoresRegioesMapaPersonalizados = new javax.swing.JCheckBox();
        cbReservas = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        cbPlanosAssinatura = new javax.swing.JCheckBox();
        cbProrcessamentoPagamento = new javax.swing.JCheckBox();
        cbCarrinhoDeCompras = new javax.swing.JCheckBox();
        cbMarketingUsuarios = new javax.swing.JCheckBox();
        cbGerenciamentoProdutos = new javax.swing.JCheckBox();
        cbComprasDentroAplicativo = new javax.swing.JCheckBox();
        cbColetaInformacoesAplicativo = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        cbPaginaAdministracaoUsuarios = new javax.swing.JCheckBox();
        cbModeracaoAprovacaoConteudo = new javax.swing.JCheckBox();
        cbIntercom = new javax.swing.JCheckBox();
        cbAnaliseUso = new javax.swing.JCheckBox();
        cbRelatorioErros = new javax.swing.JCheckBox();
        cbMonitoramentoPerformance = new javax.swing.JCheckBox();
        cbSuporteMultilingue = new javax.swing.JCheckBox();
        cbIntegracaoCMS = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        cbConectarUmOuMaisServicosDeTerceiros = new javax.swing.JCheckBox();
        cbMascaramentoNumeroTelefone = new javax.swing.JCheckBox();
        cbEnvioSMS = new javax.swing.JCheckBox();
        cbApiParaTerceiros = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        cbSegurancaBaseadaCertificadoSSL = new javax.swing.JCheckBox();
        cbProtecaoContraDos = new javax.swing.JCheckBox();
        cbAutenticacaoDuasEtapas = new javax.swing.JCheckBox();
        btnConfirmar = new javax.swing.JButton();

        jButton1.setText("Confirmar");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criar Estimativa");
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tamanho do APP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        cbGrande.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cbGrande.setText("Grande");
        cbGrande.setToolTipText("");

        cbPequeno.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cbPequeno.setText("Pequeno");
        cbPequeno.setToolTipText("");
        cbPequeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPequenoActionPerformed(evt);
            }
        });

        cbMedio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cbMedio.setText("Médio");
        cbMedio.setToolTipText("");
        cbMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMedioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(cbPequeno, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(cbMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPequeno, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nível de UI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel1.setFocusable(false);

        cbBasico.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cbBasico.setText("Básico");
        cbBasico.setToolTipText("");
        cbBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBasicoActionPerformed(evt);
            }
        });

        cbProfissional.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cbProfissional.setText("Profissional");
        cbProfissional.setToolTipText("");
        cbProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProfissionalActionPerformed(evt);
            }
        });

        cbMVP.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cbMVP.setText("MVP");
        cbMVP.setToolTipText("");
        cbMVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMVPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(cbMVP, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(cbBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMVP, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuários & Contas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        cbCadastroEmailSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCadastroEmailSenha.setText("Cadastro por E-mail e Senha");

        cbCadastroFacebook.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCadastroFacebook.setText("Cadastro pelo Facebook");

        cbEmailConviteUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbEmailConviteUsuario.setText("E-mails de Convite de Usuário");

        cbCadastroTwitter.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCadastroTwitter.setText("Cadastro pelo Twitter");

        cbCadastroGithub.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCadastroGithub.setText("Cadastro pelo GitHub");
        cbCadastroGithub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCadastroGithubActionPerformed(evt);
            }
        });

        cbCadastroLinkedin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCadastroLinkedin.setText("Cadastro pelo Linkedin");

        cbCadastroGoogle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCadastroGoogle.setText("Cadastro pelo Google");

        cbSubdominios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbSubdominios.setText("Subdomímios");

        cbContasMultiTenant.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbContasMultiTenant.setText("Contas Multi-tenant");

        cbDominiosPesonalizados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbDominiosPesonalizados.setText("Domínios Personalizados");
        cbDominiosPesonalizados.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDominiosPesonalizados, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(cbEmailConviteUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbContasMultiTenant, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(cbCadastroGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbCadastroLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(cbCadastroEmailSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(cbCadastroFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(cbCadastroTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCadastroGithub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSubdominios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCadastroEmailSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCadastroFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCadastroTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCadastroGithub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCadastroLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCadastroGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbEmailConviteUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbContasMultiTenant, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbSubdominios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(cbDominiosPesonalizados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Conteúdo Gerado Pelo Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        cbPainel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbPainel.setText("Painel (Dashboard)");

        cbFeedAtividade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbFeedAtividade.setText("Feed de Atividade");

        cbTags.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbTags.setText("Tags");

        cbUploadArquivos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbUploadArquivos.setText("Upload de Arquivos");

        cbEmailTransacionais.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbEmailTransacionais.setText("E-mails Transacionais ");
        cbEmailTransacionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEmailTransacionaisActionPerformed(evt);
            }
        });

        cbPerfisUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbPerfisUsuario.setText("Perfis de Usuário");

        cbUploadMidia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbUploadMidia.setText("Upload de Mídia");

        cbProcessamentoAudioVideo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbProcessamentoAudioVideo.setText("Processamento de Áudio/Vídeo");

        cbAvaliacoesComentarios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbAvaliacoesComentarios.setText("Avaliações ou Comentários");

        cbPesquisa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbPesquisa.setText("Pesquisa");
        cbPesquisa.setToolTipText("");

        cbPesquisaTextoLivre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbPesquisaTextoLivre.setText("Pesquisa de Texto Livre ");
        cbPesquisaTextoLivre.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cbPesquisaTextoLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(cbTags)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbAvaliacoesComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(cbUploadMidia, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbPerfisUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(cbPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cbFeedAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbEmailTransacionais, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProcessamentoAudioVideo)
                    .addComponent(cbUploadArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFeedAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUploadArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEmailTransacionais, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPerfisUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUploadMidia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTags, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAvaliacoesComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProcessamentoAudioVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPesquisaTextoLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Social & Engajamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        cbMensagens.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbMensagens.setText("Mensagens");

        cbForunsComentarios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbForunsComentarios.setText("Fóruns ou Comentários");

        cbIntegracaoFacebookOpenGraph.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbIntegracaoFacebookOpenGraph.setText("Integração com Facebook Open Graph");

        cbCompartilhamentoSocial.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCompartilhamentoSocial.setText("Compartilhamento Social");

        cbNotificacoesPush.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbNotificacoesPush.setText("Notificações Push");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbForunsComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbCompartilhamentoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbNotificacoesPush, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(cbIntegracaoFacebookOpenGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbForunsComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCompartilhamentoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbIntegracaoFacebookOpenGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNotificacoesPush, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datas & Localizações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        cbCalendario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCalendario.setText("Calendário");

        cbExibicaoDadosMapaGeolocalizacoes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbExibicaoDadosMapaGeolocalizacoes.setText("Exibição de Dados de Mapa/ Geolocalizações");

        cbExibicaoMercadoresRegioesMapaPersonalizados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbExibicaoMercadoresRegioesMapaPersonalizados.setText("Exibição de Marcadores/Regiões de Mapa Personalizados");

        cbReservas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbReservas.setText("Reservas");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbExibicaoDadosMapaGeolocalizacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbExibicaoMercadoresRegioesMapaPersonalizados, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbExibicaoDadosMapaGeolocalizacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbExibicaoMercadoresRegioesMapaPersonalizados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Faturamento & e-Commerce", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        cbPlanosAssinatura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbPlanosAssinatura.setText("Planos de Assinatura");

        cbProrcessamentoPagamento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbProrcessamentoPagamento.setText("Processamento de Pagamentos");

        cbCarrinhoDeCompras.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCarrinhoDeCompras.setText("Carrinho de Compras");

        cbMarketingUsuarios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbMarketingUsuarios.setText("Marketing de Usuários");
        cbMarketingUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMarketingUsuariosActionPerformed(evt);
            }
        });

        cbGerenciamentoProdutos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbGerenciamentoProdutos.setText("Gerenciamento de Produtos ");

        cbComprasDentroAplicativo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbComprasDentroAplicativo.setText("Compras dentro do Aplicativo");

        cbColetaInformacoesAplicativo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbColetaInformacoesAplicativo.setText("Coleta de Informações do Aplicativo");
        cbColetaInformacoesAplicativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbColetaInformacoesAplicativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPlanosAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMarketingUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProrcessamentoPagamento)
                            .addComponent(cbGerenciamentoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbComprasDentroAplicativo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCarrinhoDeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbColetaInformacoesAplicativo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPlanosAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProrcessamentoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCarrinhoDeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMarketingUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbComprasDentroAplicativo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGerenciamentoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbColetaInformacoesAplicativo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admistração, Feedback & Análises", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        cbPaginaAdministracaoUsuarios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbPaginaAdministracaoUsuarios.setText("Página de Admistração de Usuários");

        cbModeracaoAprovacaoConteudo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbModeracaoAprovacaoConteudo.setText("Moderação / Aprovação de Conteúdo");

        cbIntercom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbIntercom.setText("Intercom");

        cbAnaliseUso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbAnaliseUso.setText("Ánalise de Uso");
        cbAnaliseUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnaliseUsoActionPerformed(evt);
            }
        });

        cbRelatorioErros.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbRelatorioErros.setText("Relatório de Erros");

        cbMonitoramentoPerformance.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbMonitoramentoPerformance.setText("Monitoramento de Performance ");

        cbSuporteMultilingue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbSuporteMultilingue.setText("Suporte Multilíngue");
        cbSuporteMultilingue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSuporteMultilingueActionPerformed(evt);
            }
        });

        cbIntegracaoCMS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbIntegracaoCMS.setText("Integração com CMS");
        cbIntegracaoCMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIntegracaoCMSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbAnaliseUso, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPaginaAdministracaoUsuarios)
                    .addComponent(cbIntegracaoCMS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbModeracaoAprovacaoConteudo)
                            .addComponent(cbMonitoramentoPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRelatorioErros, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbIntercom, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbSuporteMultilingue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPaginaAdministracaoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbModeracaoAprovacaoConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbIntercom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMonitoramentoPerformance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbAnaliseUso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbRelatorioErros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSuporteMultilingue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbIntegracaoCMS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APIs Externas & Integrações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        cbConectarUmOuMaisServicosDeTerceiros.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbConectarUmOuMaisServicosDeTerceiros.setText("Conectar com um ou mais serviçoes de terceiros");

        cbMascaramentoNumeroTelefone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbMascaramentoNumeroTelefone.setText("Mascaramento de Número de Telefone ");

        cbEnvioSMS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbEnvioSMS.setText("Envio de SMS");

        cbApiParaTerceiros.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbApiParaTerceiros.setText("API para que terceiros integrem ao seu app");
        cbApiParaTerceiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbApiParaTerceirosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbConectarUmOuMaisServicosDeTerceiros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbApiParaTerceiros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMascaramentoNumeroTelefone)
                    .addComponent(cbEnvioSMS, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbConectarUmOuMaisServicosDeTerceiros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMascaramentoNumeroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbApiParaTerceiros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEnvioSMS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Segurança", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        cbSegurancaBaseadaCertificadoSSL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbSegurancaBaseadaCertificadoSSL.setText("Segurança baseada em Certificado SSL");

        cbProtecaoContraDos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbProtecaoContraDos.setText("Proteção contra DoS");

        cbAutenticacaoDuasEtapas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbAutenticacaoDuasEtapas.setText("Autenticação em Duas Etapas");
        cbAutenticacaoDuasEtapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAutenticacaoDuasEtapasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(cbSegurancaBaseadaCertificadoSSL)
                .addGap(18, 18, 18)
                .addComponent(cbProtecaoContraDos)
                .addGap(18, 18, 18)
                .addComponent(cbAutenticacaoDuasEtapas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSegurancaBaseadaCertificadoSSL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProtecaoContraDos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAutenticacaoDuasEtapas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnConfirmar.setText("Confirmar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnConfirmar)
                .addGap(15, 15, 15))
        );

        jScrollPane1.setViewportView(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2156, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPequenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPequenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPequenoActionPerformed

    private void cbBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBasicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBasicoActionPerformed

    private void cbProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProfissionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProfissionalActionPerformed

    private void cbMVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMVPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMVPActionPerformed

    private void cbCadastroGithubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCadastroGithubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCadastroGithubActionPerformed

    private void cbEmailTransacionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEmailTransacionaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEmailTransacionaisActionPerformed

    private void cbMarketingUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMarketingUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMarketingUsuariosActionPerformed

    private void cbColetaInformacoesAplicativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbColetaInformacoesAplicativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbColetaInformacoesAplicativoActionPerformed

    private void cbAnaliseUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnaliseUsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAnaliseUsoActionPerformed

    private void cbSuporteMultilingueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSuporteMultilingueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSuporteMultilingueActionPerformed

    private void cbIntegracaoCMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIntegracaoCMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIntegracaoCMSActionPerformed

    private void cbApiParaTerceirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbApiParaTerceirosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbApiParaTerceirosActionPerformed

    private void cbAutenticacaoDuasEtapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAutenticacaoDuasEtapasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAutenticacaoDuasEtapasActionPerformed

    private void cbMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoEstimativaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JCheckBox cbAnaliseUso;
    private javax.swing.JCheckBox cbApiParaTerceiros;
    private javax.swing.JCheckBox cbAutenticacaoDuasEtapas;
    private javax.swing.JCheckBox cbAvaliacoesComentarios;
    private javax.swing.JCheckBox cbBasico;
    private javax.swing.JCheckBox cbCadastroEmailSenha;
    private javax.swing.JCheckBox cbCadastroFacebook;
    private javax.swing.JCheckBox cbCadastroGithub;
    private javax.swing.JCheckBox cbCadastroGoogle;
    private javax.swing.JCheckBox cbCadastroLinkedin;
    private javax.swing.JCheckBox cbCadastroTwitter;
    private javax.swing.JCheckBox cbCalendario;
    private javax.swing.JCheckBox cbCarrinhoDeCompras;
    private javax.swing.JCheckBox cbColetaInformacoesAplicativo;
    private javax.swing.JCheckBox cbCompartilhamentoSocial;
    private javax.swing.JCheckBox cbComprasDentroAplicativo;
    private javax.swing.JCheckBox cbConectarUmOuMaisServicosDeTerceiros;
    private javax.swing.JCheckBox cbContasMultiTenant;
    private javax.swing.JCheckBox cbDominiosPesonalizados;
    private javax.swing.JCheckBox cbEmailConviteUsuario;
    private javax.swing.JCheckBox cbEmailTransacionais;
    private javax.swing.JCheckBox cbEnvioSMS;
    private javax.swing.JCheckBox cbExibicaoDadosMapaGeolocalizacoes;
    private javax.swing.JCheckBox cbExibicaoMercadoresRegioesMapaPersonalizados;
    private javax.swing.JCheckBox cbFeedAtividade;
    private javax.swing.JCheckBox cbForunsComentarios;
    private javax.swing.JCheckBox cbGerenciamentoProdutos;
    private javax.swing.JCheckBox cbGrande;
    private javax.swing.JCheckBox cbIntegracaoCMS;
    private javax.swing.JCheckBox cbIntegracaoFacebookOpenGraph;
    private javax.swing.JCheckBox cbIntercom;
    private javax.swing.JCheckBox cbMVP;
    private javax.swing.JCheckBox cbMarketingUsuarios;
    private javax.swing.JCheckBox cbMascaramentoNumeroTelefone;
    private javax.swing.JCheckBox cbMedio;
    private javax.swing.JCheckBox cbMensagens;
    private javax.swing.JCheckBox cbModeracaoAprovacaoConteudo;
    private javax.swing.JCheckBox cbMonitoramentoPerformance;
    private javax.swing.JCheckBox cbNotificacoesPush;
    private javax.swing.JCheckBox cbPaginaAdministracaoUsuarios;
    private javax.swing.JCheckBox cbPainel;
    private javax.swing.JCheckBox cbPequeno;
    private javax.swing.JCheckBox cbPerfisUsuario;
    private javax.swing.JCheckBox cbPesquisa;
    private javax.swing.JCheckBox cbPesquisaTextoLivre;
    private javax.swing.JCheckBox cbPlanosAssinatura;
    private javax.swing.JCheckBox cbProcessamentoAudioVideo;
    private javax.swing.JCheckBox cbProfissional;
    private javax.swing.JCheckBox cbProrcessamentoPagamento;
    private javax.swing.JCheckBox cbProtecaoContraDos;
    private javax.swing.JCheckBox cbRelatorioErros;
    private javax.swing.JCheckBox cbReservas;
    private javax.swing.JCheckBox cbSegurancaBaseadaCertificadoSSL;
    private javax.swing.JCheckBox cbSubdominios;
    private javax.swing.JCheckBox cbSuporteMultilingue;
    private javax.swing.JCheckBox cbTags;
    private javax.swing.JCheckBox cbUploadArquivos;
    private javax.swing.JCheckBox cbUploadMidia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
